# -------------------------------
# RNA-seq project configuration
# -------------------------------

samples:
  - control1
  - control2
  - treated1
  - treated2

raw_data_dir: data/raw
results_dir: results

reference:
  genome_index: refs/genome_index               # Bowtie2 index base name
  annotation_gtf: refs/Homo_sapiens.GRCh38.110.gtf

threads: 4
